### ISSUE TITLE
PrimaryParty arrow is many-valued, but why?

### ISSUE THREAD

**Issue by sfsinger19103** [HiltonRoscoe/CdfTools#2]
Why is the PrimaryParty arrow from CandidateContest to Party possibly many-valued?

Concretely, consider the US Senator from Oregon. In any year where a seat is open, there are three contests:
Contest for the Republican Party nomination to US Senate (voted at primary)
Contest for the Democratic Party nomination to US Senate (voted at primary)
Contest for the US Senate (voted at general)

It seems to me that (1) and (2) are each associated to one single party, while (3) is associated to no party.

What am I missing?

**Comment by JDziurlaj** [comment]
Hi @sfsinger19103,

Please open this issue under https://github.com/usnistgov/ElectionResultsReporting
